# Build Stage
FROM --platform=linux/amd64 ubuntu:20.04 as builder
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y gcc

COPY . /umka-lang
WORKDIR /umka-lang
RUN ./build_linux.sh

FROM ubuntu:20.04 as package
COPY --from=builder /umka-lang/umka_linux/umka /
COPY --from=builder /umka-lang/umka_linux/libumka.so /deps/
ENV LD_LIBRARY_PATH=/deps
